version: '3.9'

services:
  web:
    container_name: film_rental_system
    image: film_rental_system
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/postgres/data/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db-film-rental-system-week-7

  redis:
    image: redis:alpine


volumes:
  pg_data: {}