# Generated by Django 3.2 on 2022-03-10 03:16

from django.db import migrations, models
import django.db.models.deletion
import film.business_logic


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[film.business_logic.validator_no_negative])),
                ('start_date', models.DateField(validators=[film.business_logic.validator_date_limit_future])),
                ('return_date', models.DateField(validators=[film.business_logic.validator_date_limit_future])),
                ('actual_return_date', models.DateField(blank=True, null=True, validators=[film.business_logic.validator_date_limit_future])),
                ('client', models.ForeignKey(on_delete=models.Model, to='person.client')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film')),
            ],
        ),
    ]
