# Generated by Django 3.2 on 2022-03-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='state',
            field=models.CharField(choices=[('close', 'Close'), ('open', 'Open')], default='open', max_length=120),
            preserve_default=False,
        ),
    ]
