# Generated by Django 3.2 on 2022-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rent_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], max_length=120),
        ),
    ]
