# Generated by Django 3.2 on 2022-03-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('other', 'Other'), ('male', 'Male'), ('feminine', 'Feminine')], max_length=120),
        ),
    ]
