# Generated by Django 3.2 on 2022-03-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('feminine', 'Feminine'), ('other', 'Other'), ('male', 'Male')], max_length=120),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('film related', 'Film related'), ('client', 'Client')], max_length=120),
        ),
    ]
