# Generated by Django 3.2 on 2022-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20220310_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('other', 'Other'), ('feminine', 'Feminine')], max_length=120),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('client', 'Client'), ('film related', 'Film related')], max_length=120),
        ),
    ]
