# Generated by Django 3.2 on 2022-03-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20220313_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('feminine', 'Feminine'), ('other', 'Other')], max_length=120),
        ),
    ]
