# Generated by Django 3.2 on 2022-03-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('other', 'Other'), ('feminine', 'Feminine')], max_length=120),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('film related', 'Film related'), ('client', 'Client')], max_length=120),
        ),
    ]
