# Generated by Django 3.2 on 2022-03-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20220316_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('feminine', 'Feminine'), ('other', 'Other'), ('male', 'Male')], max_length=120),
        ),
    ]
