# Generated by Django 3.2 on 2022-03-10 03:16

from django.db import migrations, models
import django.db.models.deletion
import film.business_logic


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(validators=[film.business_logic.validator_date_limit_today])),
                ('price_by_day', models.DecimalField(decimal_places=2, max_digits=15, validators=[film.business_logic.validator_no_negative])),
                ('stock', models.IntegerField(validators=[film.business_logic.validator_no_negative])),
                ('availability', models.IntegerField(validators=[film.business_logic.validator_no_negative])),
                ('film_type', models.CharField(choices=[('movie', 'Movie'), ('serie', 'Serie')], max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.category')),
                ('film_prequel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film.film')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('film', models.ForeignKey(limit_choices_to={'film_type': 'serie'}, on_delete=django.db.models.deletion.CASCADE, to='film.film')),
                ('season_prequel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film.season')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('chapter_prequel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film.chapter')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.season')),
            ],
        ),
    ]
