# Generated by Django 3.2 on 2022-03-17 20:16

from django.db import migrations, models
import film.models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=film.models.upload_film_image),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('serie', 'Serie')], max_length=120),
        ),
    ]
