# Generated by Django 3.2 on 2022-03-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_alter_film_film_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('serie', 'Serie')], max_length=120),
        ),
    ]
