# Generated by Django 3.2 on 2022-03-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_alter_film_film_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_type',
            field=models.CharField(choices=[('serie', 'Serie'), ('movie', 'Movie')], max_length=120),
        ),
    ]
